CREATE TABLE cafes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    district VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    latitude NUMERIC(9, 6) NOT NULL CHECK (latitude >= -90 AND latitude <= 90),
    longitude NUMERIC(9, 6) NOT NULL CHECK (longitude >= -180 AND longitude <= 180),
    geom geography(Point, 4326) GENERATED ALWAYS AS (
        ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography
    ) STORED,
    rating NUMERIC(2, 1) NOT NULL CHECK (rating >= 0.0 AND rating <= 5.0),
    review_count INTEGER NOT NULL CHECK (review_count >= 0),
    price_level INTEGER NOT NULL CHECK (price_level >= 1 AND price_level <= 4),
    opens_at TIME NOT NULL,
    closes_at TIME NOT NULL,
    has_wifi BOOLEAN NOT NULL,
    has_power BOOLEAN NOT NULL,
    quiet_score INTEGER NOT NULL CHECK (quiet_score >= 0 AND quiet_score <= 100),
    seat_count INTEGER NOT NULL CHECK (seat_count >= 0),
    tags TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cafes_geom ON cafes USING GIST (geom);
CREATE INDEX idx_cafes_district ON cafes (district);
